language: c

os:
  - linux
  - windows
# - osx
# - freebsd

# Build matrix
compiler:
  - gcc
  - clang

env:
  - CGREEN_WITH_STATIC_LIBRARY="OFF"
  - CGREEN_WITH_STATIC_LIBRARY="ON"

addons:
  apt:
    packages:
    - cmake
    - lcov
    - g++

before_install:
  - if [[ $CC == gcc ]] ; then export CXX=g++ ; else export CXX=clang++ ; fi
  - $CC --version
  - $CXX --version
  - export build_prefix=""
  - |-
    case $TRAVIS_OS_NAME in
      linux)
        gem install coveralls-lcov
        if [ "$CC" = "gcc" ]; then export WITH_GCOV=ON; else WITH_GCOV=OFF; fi
        ;;
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2 bazel
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export shell="$msys2 -mingw64 -full-path -here -c \$\* --"
        export msys2+=" -msys2 -c \$\* --"
        $msys2 pacman --sync --noconfirm --needed \
                mingw-w64-x86_64-libtool \
                mingw-w64-x86_64-toolchain \
                cmake \
                make \
                gcc \
                clang
        taskkill //IM gpg-agent.exe //F
        export CPPFLAGS=-D__USE_MINGW_ANSI_STDIO=1
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export build_prefix="$msys2"
        ;;
    esac

script:
  - mkdir -p build
  - cd build
  - $build_prefix cmake -DCGREEN_WITH_UNIT_TESTS:BOOL=ON -DCGREEN_WITH_STATIC_LIBRARY:BOOL=$CGREEN_WITH_STATIC_LIBRARY -DCGREEN_INTERNAL_WITH_GCOV:BOOL=$WITH_GCOV ..
  - $build_prefix make -j2
  - $build_prefix ctest --output-on-failure

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "gcc" ];
    then
      lcov -d tests -d src -d tools -base-directory .. -c -o coverage.info;
      lcov --remove coverage.info '/usr/*' -o coverage.info;
      cd ..;
      coveralls-lcov build/coverage.info;
    fi

#notifications:
#  slack:
#    rooms:
#      secure: "Tobw+sqwGWscQo/mnBiO/+CQDMu8of5kXUhFKK1GblxTqxvJGGRVVvjt5ZlYaTyJD6YCzaVAO9hSjMvebnTTIqqP5WFmhpO3Du3khZJhFjzhqfjIUmK4S0rAMs3BBvLTGAUa0Hvnrt1VOkOJUdwdSW8nmnw9uFx3rVCthAOLkQugUY4s8tCc/QHBJPUSqdKntTq9e4bapaMl4gREPFvtneOyN7LQp0JtI/nyrdTVlONaqkPv7M8sEC7a6ec6RK/AiEurp8XczNW0ifTwqCg2y/sLfnRg+wzG1H9sMmzs+Kx7akcGdGzi/rqWRnBDF3mKL4pt8YhmBy/znDnMAR559puRiyz6ZZhlBKRviZrsfQmC0F3IyTZY/S3SjvatT9DrAIsHDLbDNxRxzO0GC+cpkq4HU8VnF4rQ31VVb75igMHzgw3SvDOqsZ3g0jPiBybEi0jVRUzmDWrw7p6qtl5hwQam6dxfmO6xXpwOTqPI9WQEOZeZfOw7eIeEbpB5wJ723z2cEwutoDdConIZElJBKjcjFp5rjR/yG94H/0OEgCmC/JRrdd71BB9vPh4SO40RvKkxV0adY7Xk2vkAxwLFhxS7QIdNfyQBFFEBnR+JFBHE+9XwEH1JmaAbrSYgg0+vVUZPOuqcqvz+9PUTlAb5rqYB97XEbF//5t8URrriuB0="
