option(CGREEN_WITH_STATIC_LIBRARY "Build with a static library" OFF)
option(CGREEN_WITH_UNIT_TESTS "Build unit tests" ON)
option(CGREEN_INTERNAL_WITH_GCOV "Build with test coverage instrumentation" OFF)
option(CGREEN_RUNNER_FORCE_LIBBFD "Force use of libbfd for cgreen-runner on system that have GNU dlinfo() available" OFF )
mark_as_advanced(CGREEN_INTERNAL_WITH_GCOV)
